# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Application Database Services
    App\Service\Database:
        arguments:
            $url: '%env(resolve:DATABASE_URL)%'

    App\Repository\FeatureClassRepository:
        arguments:
            $database: '@App\Service\Database'

    App\Repository\ServiceRepository:
        arguments:
            $database: '@App\Service\Database'

    # Application Encryption Services
    App\Service\Encryption:
        arguments:
            $cipher: aes-256-ccm
            $key: '%env(resolve:SSL_KEY)%'
    App\Service\EncryptInterface: '@App\Service\Encryption'
    App\Service\DecryptInterface: '@App\Service\Encryption'

